
import { Inter } from "next/font/google";
import "./globals.css";
import { ReduxProvider } from "./StoreProvider";
import NavBar from "../../components/navbar/Navbar";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
title: "Create Next App",
description: "Generated by create next app",
};

export default function RootLayout({ children }) {
return (
<>
<html lang="en">
<body className={inter.className} suppressHydrationWarning>
<ReduxProvider>
<NavBar/>
{children}
</ReduxProvider>
</body>
</html>
</>
);
}
